#argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-todo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "flask-app=nasirbloch323/helm-app"
    argocd-image-updater.argoproj.io/flask-todo.update-strategy: "semver"
    argocd-image-updater.argoproj.io/flask-todo.allow-tags: "regexp:^v?\\d+\\.\\d+\\.\\d+$"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nasirbloch323/Flask-Todo-App-Deployment-using-Kubernetes-Helm-Argo-CD-Argo-CD-Image-Updater.git
    path: flask-app
    targetRevision: argocd
   helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

